name: Instagram Bot
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      # - run: |
      #     sudo apt-get update
      #     sudo apt-get install -y xvfb libxkbcommon0 libxkbcommon-x11-0  
      - run: pip install -r requirements.txt
      - run: playwright install chromium
      - run: python main.py# When running it locally uncomment this line and comment the one below
      # - run: xvfb-run -a python main.py # When running it on GitHub comment this line and uncomment the one above
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          # DISPLAY: :99
# Added below to upload screenshots for debugging
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-screens
          path: |
            login_debug.png
            failed_login.png
